pluginManagement {
    repositories {
        maven { url "https://artifactory.apps.bancolombia.com/maven-bancolombia" }
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'CursoSpring'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':restcontroller-entry-points'
project(':restcontroller-entry-points').projectDir = file('./infrastructure/entry-points/restcontroller-entry-points')